const cookie = [
    {
        "domain": ".auto.ru",
        "expirationDate": 1666729296,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ym_visorc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "b"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669319596.059401,
        "hostOnly": false,
        "httpOnly": false,
        "name": "counter_ga_all7",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1697732341.291457,
        "hostOnly": false,
        "httpOnly": false,
        "name": "suid",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "b53ea2d03dd310573b32da7ee4593f4b.ee155a835e74b219d9660563405ccecf"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1698263596,
        "hostOnly": false,
        "httpOnly": false,
        "name": "layout-config",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "{\"win_width\":1517.77783203125,\"win_height\":730}"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1701287510.916494,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_yasc",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "GfqST7zMNIkumTcd5x7V5lYjVoYdiq0gf4ubyHzVOn4ZZElo9vzZtEm3H3uTCg=="
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1698263603.134126,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ym_uid",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1619469299519713448"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667937117,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bltsr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1701287517.130227,
        "hostOnly": false,
        "httpOnly": true,
        "name": "i",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "m6fl3MnOG/UX7K+46Mekou9PDruAdmIpQnMiq++GmzLYn/uLUuBY7QQNkQB/jA3noAdfbWDpEfaGMDMvQ5LycyP+1ps="
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1666733519,
        "hostOnly": false,
        "httpOnly": false,
        "name": "sso_status",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "sso.passport.yandex.ru:synchronized"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667842825.017254,
        "hostOnly": false,
        "httpOnly": true,
        "name": "autoru_sid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "a%3Ag6350237521t22skdld0e69ec1l7hfj3.1f6c8de2d17d4932b42bd28204bf6a80%7C1666801141457.604800.caanz3rNIyREJxlSU3NrDw.d5Kb9oeCXOtsd4PZjzj2eQXPDXlTyK3S0a_3AHRGFts"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1666734717.130004,
        "hostOnly": false,
        "httpOnly": true,
        "name": "Session_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "noauth:1666727516"
    },
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "_csrf_token",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "a6a5914db22d3c21b9cd8ca3f737fa639ec04777094262b5"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1698263603.134352,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ym_d",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1666727603"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1666799492,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ym_isad",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669225234,
        "hostOnly": false,
        "httpOnly": false,
        "name": "autoru-visits-count",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "2"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667405941.730571,
        "hostOnly": false,
        "httpOnly": true,
        "name": "autoruuid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "g6350237521t22skdld0e69ec1l7hfj3.1f6c8de2d17d4932b42bd28204bf6a80"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1666801146,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cmtchd",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "MTY2NjE5NjM0NjM2OQ=="
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667405946,
        "hostOnly": false,
        "httpOnly": false,
        "name": "crookie",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "pNSLSYq/EXnz3hjPj4ZpO6Lz+ET+xGmz34qUNtOlNmly8XlZRxhTlkC4fhUipj2LOx1iQxYo/1oAafgZwEygvGB00g8="
    },
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "from",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "yandex"
    },
    {
        "domain": ".auto.ru",
        "hostOnly": false,
        "httpOnly": false,
        "name": "from_lifetime",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "1666727601856"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1698263517,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gdpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667937117,
        "hostOnly": false,
        "httpOnly": false,
        "name": "los",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1701287517.130311,
        "hostOnly": false,
        "httpOnly": false,
        "name": "mda2_beacon",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1666727516563"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669225233.152189,
        "hostOnly": false,
        "httpOnly": false,
        "name": "safe_deal_promo",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "3"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669319510.136593,
        "hostOnly": false,
        "httpOnly": false,
        "name": "spravka",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "dD0xNjY2NzI3NTEwO2k9ODUuMjYuMTY1LjE2MztEPTMzMDRFQTk1NkExMTI4NkUzRTAwRkI2M0M5RjU5MEIxNjExOTAyMEMzQjQ2N0QwODkzNDRGNEY5MTM1M0E1NUNFQUFCODkyRTt1PTE2NjY3Mjc1MTAyMjg2NTM4ODU7aD03YzdhMWMyMDBjNjc3ZDUzZGNkMTdiNTNkZTdiNWE3Mw=="
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1698263517.130129,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yandex_login",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": ""
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669319595.395312,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yandexuid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2582876301666722099"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1669319595.395443,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ys",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "c_chck.2779159330%23wprid.1666727485496885-14629754174301370475-sas3-0677-e01-sas-l7-balancer-8080-BAL-7733"
    },
    {
        "domain": ".auto.ru",
        "expirationDate": 1667332395.395,
        "hostOnly": false,
        "httpOnly": false,
        "name": "yuidlt",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    }
]